require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FamilyMembersController do

  # This should return the minimal set of attributes required to create a valid
  # FamilyMember. As you add validations to FamilyMember, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:family_code => "abc", :firstname => "mark"}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FamilyMembersController. Be sure to keep this updated too.
  def valid_session
    {:test => true}
  end

  describe "GET show" do
    it "assigns the requested family_member as @family_member" do
      family_member = FamilyMember.create! valid_attributes
      get :show, {:id => family_member.to_param}, valid_session
      assigns(:family_member).should eq(family_member)
    end
  end

  describe "GET new" do
    it "assigns a new family_member as @family_member" do
      get :new, {}, valid_session
      assigns(:family_member).should be_a_new(FamilyMember)
    end
  end

  describe "POST create" do

    describe "with invalid params" do
      it "assigns a newly created but unsaved family_member as @family_member" do
        # Trigger the behavior that occurs when invalid params are submitted
        FamilyMember.any_instance.stub(:save).and_return(false)
        post :create, {:family_member => {}}, valid_session
        assigns(:family_member).should be_a_new(FamilyMember)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FamilyMember.any_instance.stub(:save).and_return(false)
        post :create, {:family_member => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

end
